USE hospital_management;

-- SUM QUERY --------

-- TOTAL REVENUE GENERATED BY  HOPSPITAL
SELECT SUM(total_amount) AS total_revenue
FROM Billing;

-- TOTAL BILLING AMOUNT PER PAYMENT STATUS
SELECT payment_status, SUM(total_amount) AS total_amount
FROM Billing
GROUP BY payment_status;


-- COUNT QUERY --------

-- TOTAL NUMBER OF PATIENTS
SELECT COUNT(*) AS total_patients
FROM Patient;

-- PATIENTS BY GENDER
SELECT gender, COUNT(*) AS total
FROM Patient
GROUP BY gender;


-- AVERAGE QUERY --------

-- AVERAGE TREATMENT COST
SELECT AVG(cost) AS avg_treatment_cost
FROM Treatment;

-- AVERAGE PATIENTS AGE
SELECT AVG(age) AS avg_age
FROM Patient;


-- GORUP BY --------

-- NUMBER OF PATIENTS PER CITY
SELECT address AS city, COUNT(*) AS patient_count
FROM Patient
GROUP BY address;

-- TOTAL TREATMENT COST PER APPOINTMENT
SELECT appointment_id, SUM(cost) AS total_cost
FROM Treatment
GROUP BY appointment_id;

-- TOTAL NUMBER OF APPOINTMENTS PER DOCTOR
SELECT doctor_id, COUNT(*) AS total_appointments
FROM Appointment
GROUP BY doctor_id;


-- HAVING QUERY --------

-- CITIES WITH MORE THAN 5 PATIENTS 
SELECT address AS city, COUNT(*) AS total_patients
FROM Patient
GROUP BY address
HAVING COUNT(*) > 5;

-- APPOINTMENT WHERE TOTAL COST EXCEEDS 2000
SELECT appointment_id, SUM(cost) AS total_cost
FROM Treatment
GROUP BY appointment_id
HAVING SUM(cost) > 1000;

-- AVERAGE BILLING MORE THAN 700
SELECT payment_status, AVG(total_amount) AS avg_bill
FROM Billing
GROUP BY payment_status
HAVING AVG(total_amount) > 700;













